spring:
  main:
    banner-mode: console
    allow-circular-references: true
    scheduling:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/die_bank?createDatabaseIfNotExist=true
    username: root
    password: PassPass!!01
  jpa:
    generate-ddl: false
    show-sql: false

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db.changelog/changelog-master.yaml
  server:
    port: 8080
  security:
    user:
      name: admin
      password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: bankappsend001@gmail.com
    password: mnhk mgjh vvah goic
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
   level:
    com.sun.mail: DEBUG
    javax.mail: DEBUG
#  openapi:
#      info:
#        title: Your API
#        version: 1.0.0
#      securitySchemes:
#        bearerAuth:
#          type: http
#          scheme: bearer
#          bearerFormat: JWT
#      security:
#        - bearerAuth: [ ]
#  jwt:
#    secret:
#      access: mO2clU1rRiZnwJuVqAMowf8KNnhbuceE4ecueQ0wSRlWUOy/lMxg6OLkGGpVr4dlUMZdscAEWWSzZv9sjnZheA==
#      refresh: 1oGv0JLsjUBNcmUyuJ31ad+dsla4H0NemlInOErtWp29LNqzDxtPa7T3au9GAsDA2vn98FfyVkSNX2pas2aDbw==
